<?php
/**
 * @file
 * Drufony module
 */

/**
 * Implements hook_boot().
 */
function drufony_boot() {
  Drufony\boot();
}

/**
 * Implements hook_flush_caches().
 */
function drufony_flush_caches() {
  $paths = array('var://');
  if (Drufony::hasContainer()) {
    $paths[] = Drufony::getContainer()->getParameter('kernel.cache_dir');
  }

  foreach ($paths as $path) {
    if (is_dir($path)) {
      $dir = dir($path);
      while (($entry = $dir->read()) !== FALSE) {
        if ($entry === '.' || $entry === '..') {
          continue;
        }
        $entry_path = $dir->path . DIRECTORY_SEPARATOR . $entry;
        file_unmanaged_delete_recursive($entry_path);
      }
      $dir->close();
    }
  }
  return array();
}

/**
 * Implements hook_stream_wrappers().
 */
function drufony_stream_wrappers() {
  return array(
    'var' => array(
      'name' => t('Variable files'),
      'class' => 'Drufony\\Bridge\\DrupalVarStreamWrapper',
      'description' => t('Temporary local files for upload and previews.'),
      'type' => STREAM_WRAPPERS_LOCAL_HIDDEN,
    ),
  );
}

if (!function_exists('composer_manager_register_autoloader')) {
  function composer_manager_register_autoloader() {
    require_once DRUPAL_ROOT . '/../vendor/autoload.php';
  }
}